from __future__ import annotations

import obspython as obs

FRONTEND_EVENT_NAMES: dict[obs.FrontendEvent, str] = {
    obs.OBS_FRONTEND_EVENT_STREAMING_STARTING: "OBS_FRONTEND_EVENT_STREAMING_STARTING",
    obs.OBS_FRONTEND_EVENT_STREAMING_STARTED: "OBS_FRONTEND_EVENT_STREAMING_STARTED",
    obs.OBS_FRONTEND_EVENT_STREAMING_STOPPING: "OBS_FRONTEND_EVENT_STREAMING_STOPPING",
    obs.OBS_FRONTEND_EVENT_STREAMING_STOPPED: "OBS_FRONTEND_EVENT_STREAMING_STOPPED",
    obs.OBS_FRONTEND_EVENT_RECORDING_STARTING: "OBS_FRONTEND_EVENT_RECORDING_STARTING",
    obs.OBS_FRONTEND_EVENT_RECORDING_STARTED: "OBS_FRONTEND_EVENT_RECORDING_STARTED",
    obs.OBS_FRONTEND_EVENT_RECORDING_STOPPING: "OBS_FRONTEND_EVENT_RECORDING_STOPPING",
    obs.OBS_FRONTEND_EVENT_RECORDING_STOPPED: "OBS_FRONTEND_EVENT_RECORDING_STOPPED",
    obs.OBS_FRONTEND_EVENT_SCENE_CHANGED: "OBS_FRONTEND_EVENT_SCENE_CHANGED",
    obs.OBS_FRONTEND_EVENT_SCENE_LIST_CHANGED: "OBS_FRONTEND_EVENT_SCENE_LIST_CHANGED",
    obs.OBS_FRONTEND_EVENT_TRANSITION_CHANGED: "OBS_FRONTEND_EVENT_TRANSITION_CHANGED",
    obs.OBS_FRONTEND_EVENT_TRANSITION_STOPPED: "OBS_FRONTEND_EVENT_TRANSITION_STOPPED",
    obs.OBS_FRONTEND_EVENT_TRANSITION_LIST_CHANGED: "OBS_FRONTEND_EVENT_TRANSITION_LIST_CHANGED",
    obs.OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGED: "OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGED",
    obs.OBS_FRONTEND_EVENT_SCENE_COLLECTION_LIST_CHANGED: "OBS_FRONTEND_EVENT_SCENE_COLLECTION_LIST_CHANGED",
    obs.OBS_FRONTEND_EVENT_PROFILE_CHANGED: "OBS_FRONTEND_EVENT_PROFILE_CHANGED",
    obs.OBS_FRONTEND_EVENT_PROFILE_LIST_CHANGED: "OBS_FRONTEND_EVENT_PROFILE_LIST_CHANGED",
    obs.OBS_FRONTEND_EVENT_EXIT: "OBS_FRONTEND_EVENT_EXIT",

    obs.OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTING: "OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTING",
    obs.OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTED: "OBS_FRONTEND_EVENT_REPLAY_BUFFER_STARTED",
    obs.OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPING: "OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPING",
    obs.OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPED: "OBS_FRONTEND_EVENT_REPLAY_BUFFER_STOPPED",

    obs.OBS_FRONTEND_EVENT_STUDIO_MODE_ENABLED: "OBS_FRONTEND_EVENT_STUDIO_MODE_ENABLED",
    obs.OBS_FRONTEND_EVENT_STUDIO_MODE_DISABLED: "OBS_FRONTEND_EVENT_STUDIO_MODE_DISABLED",
    obs.OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED: "OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED",

    obs.OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP: "OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP",
    obs.OBS_FRONTEND_EVENT_FINISHED_LOADING: "OBS_FRONTEND_EVENT_FINISHED_LOADING",

    obs.OBS_FRONTEND_EVENT_RECORDING_PAUSED: "OBS_FRONTEND_EVENT_RECORDING_PAUSED",
    obs.OBS_FRONTEND_EVENT_RECORDING_UNPAUSED: "OBS_FRONTEND_EVENT_RECORDING_UNPAUSED",

    obs.OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED: "OBS_FRONTEND_EVENT_TRANSITION_DURATION_CHANGED",
    obs.OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED: "OBS_FRONTEND_EVENT_REPLAY_BUFFER_SAVED",

    obs.OBS_FRONTEND_EVENT_VIRTUALCAM_STARTED: "OBS_FRONTEND_EVENT_VIRTUALCAM_STARTED",
    obs.OBS_FRONTEND_EVENT_VIRTUALCAM_STOPPED: "OBS_FRONTEND_EVENT_VIRTUALCAM_STOPPED",

    obs.OBS_FRONTEND_EVENT_TBAR_VALUE_CHANGED: "OBS_FRONTEND_EVENT_TBAR_VALUE_CHANGED",
    obs.OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGING: "OBS_FRONTEND_EVENT_SCENE_COLLECTION_CHANGING",
    obs.OBS_FRONTEND_EVENT_PROFILE_CHANGING: "OBS_FRONTEND_EVENT_PROFILE_CHANGING",
    obs.OBS_FRONTEND_EVENT_SCRIPTING_SHUTDOWN: "OBS_FRONTEND_EVENT_SCRIPTING_SHUTDOWN",
    obs.OBS_FRONTEND_EVENT_PROFILE_RENAMED: "OBS_FRONTEND_EVENT_PROFILE_RENAMED",
    obs.OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED: "OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED",
    obs.OBS_FRONTEND_EVENT_THEME_CHANGED: "OBS_FRONTEND_EVENT_THEME_CHANGED",
    obs.OBS_FRONTEND_EVENT_SCREENSHOT_TAKEN: "OBS_FRONTEND_EVENT_SCREENSHOT_TAKEN",
}
